import type {
  LegalEntity,
  Department,
  BizLine,
  Position,
  Employee,
  RecruitmentNeed,
  SalaryApproval,
  OnboardingRecord,
  AttendanceRecord,
  AttendanceSummary,
  AttendanceException,
  KPITemplate,
  PerformanceRecord,
  PayrollRecord,
  ResignationRecord,
  Dispatch,
  DashboardStats,
} from './types'

export function generateEmployeeNo(): string {
  const now = new Date()
  const year = now.getFullYear()
  const seq = String(Math.floor(Math.random() * 999) + 1).padStart(3, '0')
  return `HX-${year}-${seq}`
}

export function formatSalary(n: number): string {
  return `¥${n.toLocaleString('zh-CN')}`
}

export function getDaysInMonth(year: number, month: number): number {
  return new Date(year, month, 0).getDate()
}

export const LEGAL_ENTITIES: LegalEntity[] = [
  {
    id: 'le-001',
    name: '深圳前海智学教育科技有限公司',
    creditCode: '91440300MA5G2XYZ01',
    address: '深圳市南山区前海深港合作区前湾一路1号A栋201室',
    contact: '张明华',
  },
  {
    id: 'le-002',
    name: '深圳XX软件科技有限公司',
    creditCode: '91440300MA5F9ABC02',
    address: '深圳市福田区华强北街道赛格广场18楼1803室',
    contact: '李文静',
  },
]

export const DEPARTMENTS: Department[] = [
  {
    id: 'dept-001',
    name: '产品部',
    parentId: null,
    leaderId: 'emp-004',
    children: [],
  },
  {
    id: 'dept-002',
    name: '技术部',
    parentId: null,
    leaderId: 'emp-002',
    children: [
      {
        id: 'dept-002-1',
        name: '前端组',
        parentId: 'dept-002',
        leaderId: 'emp-001',
      },
      {
        id: 'dept-002-2',
        name: '后端组',
        parentId: 'dept-002',
        leaderId: 'emp-003',
      },
      {
        id: 'dept-002-3',
        name: '测试组',
        parentId: 'dept-002',
        leaderId: 'emp-012',
      },
    ],
  },
  {
    id: 'dept-003',
    name: '设计部',
    parentId: null,
    leaderId: 'emp-005',
    children: [],
  },
  {
    id: 'dept-004',
    name: '销售部',
    parentId: null,
    leaderId: 'emp-006',
    children: [],
  },
  {
    id: 'dept-005',
    name: '运营部',
    parentId: null,
    leaderId: 'emp-007',
    children: [],
  },
  {
    id: 'dept-006',
    name: '行政财务部',
    parentId: null,
    leaderId: 'emp-008',
    children: [],
  },
]

export const BIZ_LINES: BizLine[] = [
  {
    id: 'biz-001',
    name: '软件定制开发',
    leaderId: 'emp-002',
    description: '为企业客户提供B端管理系统、小程序、APP等定制化软件开发服务',
  },
  {
    id: 'biz-002',
    name: 'IP打造',
    leaderId: 'emp-007',
    description: '个人IP策划、内容运营、短视频拍摄、直播带货全链路孵化',
  },
  {
    id: 'biz-003',
    name: '移民业务',
    leaderId: 'emp-006',
    description: '美国、加拿大、澳洲等主流国家投资移民及技术移民咨询服务',
  },
  {
    id: 'biz-004',
    name: '电商业务',
    leaderId: 'emp-007',
    description: '跨境电商及国内电商平台店铺运营、选品、投放、客服一站式服务',
  },
]

export const POSITIONS: Position[] = [
  { id: 'pos-001', name: '前端开发', level: 'L5', description: '负责Web前端及移动端页面开发，掌握React/Vue等主流框架' },
  { id: 'pos-002', name: '后端开发', level: 'L6', description: '负责服务端架构设计与开发，掌握Java/Python/Go等后端语言' },
  { id: 'pos-003', name: 'UI设计师', level: 'L4', description: '负责产品界面视觉设计及交互原型输出' },
  { id: 'pos-004', name: '产品经理', level: 'L7', description: '负责产品规划、需求分析、原型设计及项目推进' },
  { id: 'pos-005', name: '销售经理', level: 'L6', description: '负责客户开拓、商务谈判、合同签约及团队管理' },
  { id: 'pos-006', name: '运营专员', level: 'L3', description: '负责各平台账号运营、内容发布、数据监控及用户增长' },
  { id: 'pos-007', name: 'HR专员', level: 'L4', description: '负责招聘、入离职办理、考勤管理及员工关系维护' },
  { id: 'pos-008', name: '测试工程师', level: 'L5', description: '负责测试用例编写、功能测试、自动化测试及缺陷跟踪' },
]

export const EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    employeeNo: 'HX-2024-001',
    name: '陈志远',
    gender: '男',
    phone: '13800138001',
    idCard: '440301199201011234',
    bankAccount: '6225882012340001',
    bankName: '招商银行深圳分行',
    avatar: '/avatars/emp-001.jpg',
    legalEntityId: 'le-002',
    departmentId: 'dept-002-1',
    departmentName: '前端组',
    directLeaderId: 'emp-002',
    directLeaderName: '王建国',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: '前端开发',
    level: 'L6',
    joinDate: '2024-03-15',
    trialStatus: '已通过',
    probationEndDate: '2024-06-15',
    baseSalary: 18000,
    performanceBase: 5000,
    status: '在职',
    education: '本科',
    email: 'chenzhiyuan@hubx.com',
    emergencyContact: '陈晓红',
    emergencyPhone: '13900139001',
  },
  {
    id: 'emp-002',
    employeeNo: 'HX-2023-002',
    name: '王建国',
    gender: '男',
    phone: '13800138002',
    idCard: '440301199005052345',
    bankAccount: '6225882012340002',
    bankName: '招商银行深圳分行',
    avatar: '/avatars/emp-002.jpg',
    legalEntityId: 'le-002',
    departmentId: 'dept-002',
    departmentName: '技术部',
    directLeaderId: 'emp-009',
    directLeaderName: '张明华',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: '后端开发',
    level: 'L8',
    joinDate: '2023-06-01',
    trialStatus: '已通过',
    probationEndDate: '2023-12-01',
    baseSalary: 28000,
    performanceBase: 8000,
    status: '在职',
    education: '硕士',
    email: 'wangjianguo@hubx.com',
    emergencyContact: '王丽',
    emergencyPhone: '13900139002',
  },
  {
    id: 'emp-003',
    employeeNo: 'HX-2024-003',
    name: '刘思琪',
    gender: '女',
    phone: '13800138003',
    idCard: '440301199508123456',
    bankAccount: '6225882012340003',
    bankName: '工商银行深圳支行',
    avatar: '/avatars/emp-003.jpg',
    legalEntityId: 'le-002',
    departmentId: 'dept-002-2',
    departmentName: '后端组',
    directLeaderId: 'emp-002',
    directLeaderName: '王建国',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: '后端开发',
    level: 'L5',
    joinDate: '2024-07-10',
    trialStatus: '已通过',
    probationEndDate: '2024-10-10',
    baseSalary: 16000,
    performanceBase: 4000,
    status: '在职',
    education: '本科',
    email: 'liusiqi@hubx.com',
    emergencyContact: '刘伟',
    emergencyPhone: '13900139003',
  },
  {
    id: 'emp-004',
    employeeNo: 'HX-2023-004',
    name: '赵雅琴',
    gender: '女',
    phone: '13800138004',
    idCard: '440301199103034567',
    bankAccount: '6225882012340004',
    bankName: '建设银行深圳分行',
    avatar: '/avatars/emp-004.jpg',
    legalEntityId: 'le-001',
    departmentId: 'dept-001',
    departmentName: '产品部',
    directLeaderId: 'emp-009',
    directLeaderName: '张明华',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: '产品经理',
    level: 'L7',
    joinDate: '2023-04-01',
    trialStatus: '已通过',
    probationEndDate: '2023-10-01',
    baseSalary: 22000,
    performanceBase: 6000,
    status: '在职',
    education: '本科',
    email: 'zhaoyaqin@hubx.com',
    emergencyContact: '赵刚',
    emergencyPhone: '13900139004',
  },
  {
    id: 'emp-005',
    employeeNo: 'HX-2024-005',
    name: '孙小明',
    gender: '男',
    phone: '13800138005',
    idCard: '440301199607155678',
    bankAccount: '6225882012340005',
    bankName: '招商银行深圳分行',
    avatar: '/avatars/emp-005.jpg',
    legalEntityId: 'le-002',
    departmentId: 'dept-003',
    departmentName: '设计部',
    directLeaderId: 'emp-004',
    directLeaderName: '赵雅琴',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: 'UI设计师',
    level: 'L5',
    joinDate: '2024-09-01',
    trialStatus: '已通过',
    probationEndDate: '2025-03-01',
    baseSalary: 14000,
    performanceBase: 3000,
    status: '在职',
    education: '本科',
    email: 'sunxiaoming@hubx.com',
    emergencyContact: '孙丽华',
    emergencyPhone: '13900139005',
  },
  {
    id: 'emp-006',
    employeeNo: 'HX-2023-006',
    name: '周海涛',
    gender: '男',
    phone: '13800138006',
    idCard: '440301198809206789',
    bankAccount: '6225882012340006',
    bankName: '中国银行深圳分行',
    avatar: '/avatars/emp-006.jpg',
    legalEntityId: 'le-001',
    departmentId: 'dept-004',
    departmentName: '销售部',
    directLeaderId: 'emp-009',
    directLeaderName: '张明华',
    bizLineId: 'biz-003',
    bizLineName: '移民业务',
    position: '销售经理',
    level: 'L7',
    joinDate: '2023-02-20',
    trialStatus: '已通过',
    probationEndDate: '2023-08-20',
    baseSalary: 20000,
    performanceBase: 10000,
    status: '在职',
    education: '本科',
    email: 'zhouhaitao@hubx.com',
    emergencyContact: '周敏',
    emergencyPhone: '13900139006',
  },
  {
    id: 'emp-007',
    employeeNo: 'HX-2025-007',
    name: '林美玲',
    gender: '女',
    phone: '13800138007',
    idCard: '440301199712087890',
    bankAccount: '6225882012340007',
    bankName: '招商银行深圳分行',
    avatar: '/avatars/emp-007.jpg',
    legalEntityId: 'le-001',
    departmentId: 'dept-005',
    departmentName: '运营部',
    directLeaderId: 'emp-009',
    directLeaderName: '张明华',
    bizLineId: 'biz-002',
    bizLineName: 'IP打造',
    position: '运营专员',
    level: 'L4',
    joinDate: '2025-01-06',
    trialStatus: '已通过',
    probationEndDate: '2025-07-06',
    baseSalary: 10000,
    performanceBase: 2000,
    status: '在职',
    education: '本科',
    email: 'linmeiling@hubx.com',
    emergencyContact: '林建华',
    emergencyPhone: '13900139007',
  },
  {
    id: 'emp-008',
    employeeNo: 'HX-2024-008',
    name: '吴静怡',
    gender: '女',
    phone: '13800138008',
    idCard: '440301199402258901',
    bankAccount: '6225882012340008',
    bankName: '工商银行深圳支行',
    avatar: '/avatars/emp-008.jpg',
    legalEntityId: 'le-001',
    departmentId: 'dept-006',
    departmentName: '行政财务部',
    directLeaderId: 'emp-009',
    directLeaderName: '张明华',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: 'HR专员',
    level: 'L4',
    joinDate: '2024-05-08',
    trialStatus: '已通过',
    probationEndDate: '2024-11-08',
    baseSalary: 12000,
    performanceBase: 2000,
    status: '在职',
    education: '本科',
    email: 'wujingyi@hubx.com',
    emergencyContact: '吴强',
    emergencyPhone: '13900139008',
  },
  {
    id: 'emp-009',
    employeeNo: 'HX-2022-009',
    name: '张明华',
    gender: '男',
    phone: '13800138009',
    idCard: '440301198501010012',
    bankAccount: '6225882012340009',
    bankName: '招商银行深圳分行',
    avatar: '/avatars/emp-009.jpg',
    legalEntityId: 'le-001',
    departmentId: 'dept-001',
    departmentName: '产品部',
    directLeaderId: '',
    directLeaderName: '',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: '产品经理',
    level: 'L10',
    joinDate: '2022-01-10',
    trialStatus: '已通过',
    probationEndDate: '2022-07-10',
    baseSalary: 40000,
    performanceBase: 15000,
    status: '在职',
    education: '硕士',
    email: 'zhangminghua@hubx.com',
    emergencyContact: '李芳',
    emergencyPhone: '13900139009',
  },
  {
    id: 'emp-010',
    employeeNo: 'HX-2026-010',
    name: '黄伟杰',
    gender: '男',
    phone: '13800138010',
    idCard: '440301199906101122',
    bankAccount: '6225882012340010',
    bankName: '建设银行深圳分行',
    avatar: '/avatars/emp-010.jpg',
    legalEntityId: 'le-002',
    departmentId: 'dept-002-1',
    departmentName: '前端组',
    directLeaderId: 'emp-001',
    directLeaderName: '陈志远',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: '前端开发',
    level: 'L3',
    joinDate: '2026-07-14',
    trialStatus: '试岗中',
    probationEndDate: null,
    baseSalary: 12000,
    performanceBase: 3000,
    status: '试岗中',
    education: '本科',
    email: 'huangweijie@hubx.com',
    emergencyContact: '黄建平',
    emergencyPhone: '13900139010',
  },
  {
    id: 'emp-011',
    employeeNo: 'HX-2026-011',
    name: '郑雨萱',
    gender: '女',
    phone: '13800138011',
    idCard: '440301200001052233',
    bankAccount: '6225882012340011',
    bankName: '招商银行深圳分行',
    avatar: '/avatars/emp-011.jpg',
    legalEntityId: 'le-001',
    departmentId: 'dept-005',
    departmentName: '运营部',
    directLeaderId: 'emp-007',
    directLeaderName: '林美玲',
    bizLineId: 'biz-004',
    bizLineName: '电商业务',
    position: '运营专员',
    level: 'L3',
    joinDate: '2026-07-01',
    trialStatus: '已通过',
    probationEndDate: '2027-01-01',
    baseSalary: 9000,
    performanceBase: 2000,
    status: '试用期',
    education: '大专',
    email: 'zhengyuxuan@hubx.com',
    emergencyContact: '郑明',
    emergencyPhone: '13900139011',
  },
  {
    id: 'emp-012',
    employeeNo: 'HX-2025-012',
    name: '何志强',
    gender: '男',
    phone: '13800138012',
    idCard: '440301199305183344',
    bankAccount: '6225882012340012',
    bankName: '中国银行深圳分行',
    avatar: '/avatars/emp-012.jpg',
    legalEntityId: 'le-002',
    departmentId: 'dept-002-3',
    departmentName: '测试组',
    directLeaderId: 'emp-002',
    directLeaderName: '王建国',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    position: '测试工程师',
    level: 'L4',
    joinDate: '2025-03-10',
    trialStatus: '已通过',
    probationEndDate: '2025-09-10',
    baseSalary: 13000,
    performanceBase: 3000,
    status: '已离职',
    education: '本科',
    email: 'hezhiqiang@hubx.com',
    emergencyContact: '何秀英',
    emergencyPhone: '13900139012',
  },
]

export const RECRUITMENT_NEEDS: RecruitmentNeed[] = [
  {
    id: 'rec-001',
    position: '前端开发',
    departmentId: 'dept-002-1',
    departmentName: '前端组',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    headcount: 2,
    status: '招聘中',
    urgentLevel: '高',
    requestDate: '2026-06-15',
    expectedDate: '2026-08-15',
    description: '要求3年以上React/Vue开发经验，有B端管理系统开发经验优先，熟悉TypeScript',
    candidates: [
      {
        id: 'cand-001',
        name: '马天宇',
        phone: '15900159001',
        email: 'matianyu@163.com',
        resumeUrl: '/resumes/cand-001.pdf',
        parsedResume: {
          name: '马天宇',
          phone: '15900159001',
          email: 'matianyu@163.com',
          education: '本科',
          workYears: 4,
          skills: ['React', 'Vue3', 'TypeScript', 'Node.js', 'Webpack'],
          lastCompany: '腾讯科技',
          lastPosition: '高级前端开发',
          expectedSalary: '18-22K',
          selfIntro: '4年前端开发经验，主导过多个B端项目的前端架构设计与开发',
        },
        stage: '面试中',
        matchScore: 92,
        interviewNotes: '技术功底扎实，项目经验丰富，沟通能力良好',
        interviewScore: 88,
        recruitmentId: 'rec-001',
      },
      {
        id: 'cand-002',
        name: '杨思远',
        phone: '15900159002',
        email: 'yangsiyuan@qq.com',
        resumeUrl: '/resumes/cand-002.pdf',
        parsedResume: {
          name: '杨思远',
          phone: '15900159002',
          email: 'yangsiyuan@qq.com',
          education: '硕士',
          workYears: 2,
          skills: ['React', 'TypeScript', 'TailwindCSS', 'Next.js'],
          lastCompany: '字节跳动',
          lastPosition: '前端开发',
          expectedSalary: '15-18K',
          selfIntro: '2年大厂前端开发经验，学习能力强，对新技术敏感',
        },
        stage: '待定薪',
        matchScore: 85,
        interviewNotes: '基础扎实，但B端经验偏少，需要培养',
        interviewScore: 80,
        recruitmentId: 'rec-001',
      },
    ],
  },
  {
    id: 'rec-002',
    position: '销售经理',
    departmentId: 'dept-004',
    departmentName: '销售部',
    bizLineId: 'biz-003',
    bizLineName: '移民业务',
    headcount: 1,
    status: '招聘中',
    urgentLevel: '中',
    requestDate: '2026-07-01',
    expectedDate: '2026-09-01',
    description: '要求5年以上移民行业销售经验，有丰富的客户资源，英语流利优先',
    candidates: [
      {
        id: 'cand-003',
        name: '田雨晴',
        phone: '15900159003',
        email: 'tianyuqing@126.com',
        resumeUrl: '/resumes/cand-003.pdf',
        parsedResume: {
          name: '田雨晴',
          phone: '15900159003',
          email: 'tianyuqing@126.com',
          education: '本科',
          workYears: 7,
          skills: ['商务谈判', '客户关系管理', '英语CET-6', '团队管理'],
          lastCompany: '环球移民',
          lastPosition: '资深移民顾问',
          expectedSalary: '15-20K+提成',
          selfIntro: '7年移民行业经验，累计服务客户超300组，年均签单额超2000万',
        },
        stage: '简历筛选',
        matchScore: 78,
        interviewNotes: '',
        interviewScore: 0,
        recruitmentId: 'rec-002',
      },
    ],
  },
  {
    id: 'rec-003',
    position: '后端开发',
    departmentId: 'dept-002-2',
    departmentName: '后端组',
    bizLineId: 'biz-001',
    bizLineName: '软件定制开发',
    headcount: 1,
    status: '已到岗',
    urgentLevel: '低',
    requestDate: '2026-04-10',
    expectedDate: '2026-06-10',
    description: '要求3年以上Python/Java开发经验，熟悉微服务架构，有AI项目经验优先',
    candidates: [
      {
        id: 'cand-004',
        name: '刘思琪',
        phone: '13800138003',
        email: 'liusiqi@hubx.com',
        resumeUrl: '/resumes/cand-004.pdf',
        parsedResume: {
          name: '刘思琪',
          phone: '13800138003',
          email: 'liusiqi@hubx.com',
          education: '本科',
          workYears: 3,
          skills: ['Python', 'Java', 'FastAPI', 'Spring Boot', 'PostgreSQL'],
          lastCompany: '华为技术',
          lastPosition: '后端开发工程师',
          expectedSalary: '16-18K',
          selfIntro: '3年后端开发经验，熟悉微服务架构设计，有AI项目落地经验',
        },
        stage: '已入职',
        matchScore: 95,
        interviewNotes: '技术能力出色，项目经验匹配度高，团队协作意识强',
        interviewScore: 93,
        recruitmentId: 'rec-003',
      },
    ],
  },
]

export const SALARY_APPROVALS: SalaryApproval[] = [
  {
    id: 'sa-001',
    candidateId: 'cand-002',
    candidateName: '杨思远',
    position: '前端开发',
    departmentName: '前端组',
    bizLineName: '软件定制开发',
    proposedBaseSalary: 16000,
    proposedPerformanceBase: 4000,
    proposedProbationSalary: 14000,
    trialPeriodDays: 5,
    probationMonths: 3,
    approvalStatus: '待审批',
    hrComment: '候选人2年大厂经验，技术基础扎实，建议给予L4定级，试岗5天后进入3个月试用期',
    bossComment: '',
    aiSuggestion: '基于市场薪酬数据，该岗位L4级别薪资范围为14K-18K，建议定薪16K处于中位值，合理。绩效基数4K占比较高(25%)，建议适当降低至3K以控制固定成本。',
    createdAt: '2026-07-20',
  },
  {
    id: 'sa-002',
    candidateId: 'cand-003',
    candidateName: '田雨晴',
    position: '销售经理',
    departmentName: '销售部',
    bizLineName: '移民业务',
    proposedBaseSalary: 18000,
    proposedPerformanceBase: 12000,
    proposedProbationSalary: 16000,
    trialPeriodDays: 5,
    probationMonths: 3,
    approvalStatus: '已通过',
    hrComment: '候选人7年移民行业经验，资源丰富，建议高绩效基数以激励业绩产出',
    bossComment: '同意，销售岗位绩效占比可以适当提高',
    aiSuggestion: '销售岗位绩效基数12K占比40%较为激进，但符合行业惯例。建议设置明确的月度签单指标(≥3单)以确保绩效考核的可量化性。',
    createdAt: '2026-07-10',
  },
]

export const ONBOARDING_RECORDS: OnboardingRecord[] = [
  {
    id: 'onb-001',
    employeeId: 'emp-010',
    employeeName: '黄伟杰',
    position: '前端开发',
    departmentName: '前端组',
    joinDate: '2026-07-14',
    trialStartDate: '2026-07-14',
    trialEndDate: '2026-07-18',
    status: '试岗中',
    documentsSubmitted: true,
    trialAgreementSigned: true,
    laborContractSigned: false,
    trialEvaluation: null,
  },
  {
    id: 'onb-002',
    employeeId: 'emp-011',
    employeeName: '郑雨萱',
    position: '运营专员',
    departmentName: '运营部',
    joinDate: '2026-07-01',
    trialStartDate: '2026-07-01',
    trialEndDate: '2026-07-05',
    status: '已转正',
    documentsSubmitted: true,
    trialAgreementSigned: true,
    laborContractSigned: true,
    trialEvaluation: {
      attendance: '全勤',
      tasksCompleted: 4,
      totalHours: 40,
      communicationScore: 85,
      overallScore: 82,
      result: '通过',
      comment: '试岗期间表现积极，能快速融入团队，任务完成质量达标，建议继续观察',
      evaluator: '林美玲',
      evaluatedAt: '2026-07-05',
    },
  },
  {
    id: 'onb-003',
    employeeId: '',
    employeeName: '李明远',
    position: 'UI设计师',
    departmentName: '设计部',
    joinDate: '2026-08-01',
    trialStartDate: '2026-08-01',
    trialEndDate: '2026-08-05',
    status: '待入职',
    documentsSubmitted: false,
    trialAgreementSigned: false,
    laborContractSigned: false,
    trialEvaluation: null,
  },
]

export const ATTENDANCE_RECORDS: AttendanceRecord[] = [
  { id: 'att-001', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-01', clockIn: '09:02', clockOut: '18:35', status: '正常', remark: '' },
  { id: 'att-002', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-02', clockIn: '09:15', clockOut: '18:30', status: '迟到', remark: '地铁故障，迟到15分钟' },
  { id: 'att-003', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-03', clockIn: '08:55', clockOut: '18:40', status: '正常', remark: '' },
  { id: 'att-004', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-04', clockIn: '09:00', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-005', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-07', clockIn: '08:50', clockOut: '18:45', status: '正常', remark: '' },
  { id: 'att-006', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-08', clockIn: '09:05', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-007', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-09', clockIn: null, clockOut: null, status: '请假', remark: '年假1天' },
  { id: 'att-008', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-10', clockIn: '09:00', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-009', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-11', clockIn: '08:55', clockOut: '20:30', status: '正常', remark: '加班2小时' },
  { id: 'att-010', employeeId: 'emp-001', employeeName: '陈志远', date: '2026-07-14', clockIn: '09:10', clockOut: '18:30', status: '迟到', remark: '迟到10分钟' },
  { id: 'att-011', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-01', clockIn: '08:45', clockOut: '19:00', status: '正常', remark: '' },
  { id: 'att-012', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-02', clockIn: '08:50', clockOut: '19:15', status: '正常', remark: '' },
  { id: 'att-013', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-03', clockIn: '08:40', clockOut: '18:50', status: '正常', remark: '' },
  { id: 'att-014', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-04', clockIn: '08:55', clockOut: '19:30', status: '正常', remark: '' },
  { id: 'att-015', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-07', clockIn: '08:30', clockOut: '20:00', status: '正常', remark: '项目上线加班' },
  { id: 'att-016', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-08', clockIn: '08:50', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-017', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-09', clockIn: '08:45', clockOut: '18:40', status: '正常', remark: '' },
  { id: 'att-018', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-10', clockIn: '09:00', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-019', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-11', clockIn: '08:50', clockOut: '18:35', status: '正常', remark: '' },
  { id: 'att-020', employeeId: 'emp-002', employeeName: '王建国', date: '2026-07-14', clockIn: '08:40', clockOut: '19:00', status: '正常', remark: '' },
  { id: 'att-021', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-01', clockIn: '09:05', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-022', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-02', clockIn: '09:00', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-023', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-03', clockIn: '09:25', clockOut: '18:30', status: '迟到', remark: '迟到25分钟' },
  { id: 'att-024', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-04', clockIn: '08:55', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-025', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-07', clockIn: '09:00', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-026', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-08', clockIn: '08:55', clockOut: '17:00', status: '早退', remark: '身体不适早退' },
  { id: 'att-027', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-09', clockIn: null, clockOut: null, status: '请假', remark: '病假1天' },
  { id: 'att-028', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-10', clockIn: '09:00', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-029', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-11', clockIn: '09:00', clockOut: '18:30', status: '正常', remark: '' },
  { id: 'att-030', employeeId: 'emp-003', employeeName: '刘思琪', date: '2026-07-14', clockIn: '08:50', clockOut: '18:40', status: '正常', remark: '' },
]

export const ATTENDANCE_SUMMARIES: AttendanceSummary[] = [
  {
    employeeId: 'emp-001',
    employeeName: '陈志远',
    departmentName: '前端组',
    year: 2026,
    month: 7,
    workDays: 23,
    actualDays: 22,
    lateCount: 2,
    earlyLeaveCount: 0,
    absentDays: 0,
    leaveDays: 1,
    leaveDetails: [{ type: '年假', days: 1 }],
    overtimeHours: 2,
    deduction: 0,
  },
  {
    employeeId: 'emp-002',
    employeeName: '王建国',
    departmentName: '技术部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualDays: 23,
    lateCount: 0,
    earlyLeaveCount: 0,
    absentDays: 0,
    leaveDays: 0,
    leaveDetails: [],
    overtimeHours: 8,
    deduction: 0,
  },
  {
    employeeId: 'emp-003',
    employeeName: '刘思琪',
    departmentName: '后端组',
    year: 2026,
    month: 7,
    workDays: 23,
    actualDays: 21,
    lateCount: 1,
    earlyLeaveCount: 1,
    absentDays: 0,
    leaveDays: 1,
    leaveDetails: [{ type: '病假', days: 1 }],
    overtimeHours: 0,
    deduction: 100,
  },
  {
    employeeId: 'emp-006',
    employeeName: '周海涛',
    departmentName: '销售部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualDays: 20,
    lateCount: 0,
    earlyLeaveCount: 0,
    absentDays: 0,
    leaveDays: 3,
    leaveDetails: [{ type: '出差', days: 3 }],
    overtimeHours: 0,
    deduction: 0,
  },
  {
    employeeId: 'emp-007',
    employeeName: '林美玲',
    departmentName: '运营部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualDays: 23,
    lateCount: 0,
    earlyLeaveCount: 0,
    absentDays: 0,
    leaveDays: 0,
    leaveDetails: [],
    overtimeHours: 5,
    deduction: 0,
  },
  {
    employeeId: 'emp-004',
    employeeName: '赵雅琴',
    departmentName: '产品部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualDays: 22,
    lateCount: 1,
    earlyLeaveCount: 0,
    absentDays: 0,
    leaveDays: 1,
    leaveDetails: [{ type: '事假', days: 1 }],
    overtimeHours: 4,
    deduction: 0,
  },
]

export const ATTENDANCE_EXCEPTIONS: AttendanceException[] = [
  {
    id: 'exc-001',
    employeeId: 'emp-001',
    employeeName: '陈志远',
    type: '补卡',
    bizLineName: '软件定制开发',
    startDate: '2026-07-02',
    endDate: '2026-07-02',
    location: '深圳办公室',
    reason: '地铁1号线信号故障导致延误，已在企业微信报备',
    status: '已通过',
    approver: '王建国',
    approvedAt: '2026-07-02T10:30:00',
  },
  {
    id: 'exc-002',
    employeeId: 'emp-003',
    employeeName: '刘思琪',
    type: '请假',
    bizLineName: '软件定制开发',
    startDate: '2026-07-09',
    endDate: '2026-07-09',
    location: '',
    reason: '急性肠胃炎，需就医休息一天',
    status: '已通过',
    approver: '王建国',
    approvedAt: '2026-07-09T08:15:00',
  },
  {
    id: 'exc-003',
    employeeId: 'emp-006',
    employeeName: '周海涛',
    type: '出差',
    bizLineName: '移民业务',
    startDate: '2026-07-14',
    endDate: '2026-07-16',
    location: '广州',
    reason: '拜访广州意向移民客户，洽谈EB-5投资移民方案',
    status: '已通过',
    approver: '张明华',
    approvedAt: '2026-07-13T16:00:00',
  },
  {
    id: 'exc-004',
    employeeId: 'emp-010',
    employeeName: '黄伟杰',
    type: '补卡',
    bizLineName: '软件定制开发',
    startDate: '2026-07-16',
    endDate: '2026-07-16',
    location: '深圳办公室',
    reason: '忘记打卡，实际已在工位工作',
    status: '待审批',
    approver: '陈志远',
    approvedAt: null,
  },
  {
    id: 'exc-005',
    employeeId: 'emp-005',
    employeeName: '孙小明',
    type: '请假',
    bizLineName: '软件定制开发',
    startDate: '2026-07-21',
    endDate: '2026-07-22',
    location: '',
    reason: '家中老人住院，需陪同就医',
    status: '待审批',
    approver: '赵雅琴',
    approvedAt: null,
  },
]

export const KPI_TEMPLATES: KPITemplate[] = [
  {
    id: 'kpi-001',
    name: '前端开发绩效考核模板',
    position: '前端开发',
    items: [
      { id: 'kpi-001-1', name: '需求交付及时率', weight: 30, targetValue: '≥95%', description: '按排期准时交付需求的比例' },
      { id: 'kpi-001-2', name: '代码质量', weight: 25, targetValue: 'CR通过率≥90%', description: '代码评审通过率及Bug数量' },
      { id: 'kpi-001-3', name: '页面性能优化', weight: 15, targetValue: 'LCP<2s', description: '核心页面加载性能指标' },
      { id: 'kpi-001-4', name: '技术分享与沉淀', weight: 10, targetValue: '月度≥1次', description: '技术分享、文档沉淀、组件复用贡献' },
      { id: 'kpi-001-5', name: '团队协作', weight: 10, targetValue: '360评分≥80', description: '跨部门协作满意度及沟通效率' },
      { id: 'kpi-001-6', name: '自驱学习', weight: 10, targetValue: '季度≥1项新技术', description: '主动学习新技术并应用于项目' },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'kpi-002',
    name: '后端开发绩效考核模板',
    position: '后端开发',
    items: [
      { id: 'kpi-002-1', name: '需求交付及时率', weight: 25, targetValue: '≥95%', description: '按排期准时交付需求的比例' },
      { id: 'kpi-002-2', name: '系统稳定性', weight: 25, targetValue: '可用性≥99.9%', description: '服务可用性、故障响应及修复速度' },
      { id: 'kpi-002-3', name: '代码质量', weight: 20, targetValue: 'CR通过率≥90%', description: '代码评审通过率及线上Bug数' },
      { id: 'kpi-002-4', name: '接口性能', weight: 15, targetValue: 'P99<200ms', description: '核心接口响应时间及吞吐量' },
      { id: 'kpi-002-5', name: '技术沉淀', weight: 10, targetValue: '月度≥1篇', description: '技术文档、架构设计文档输出' },
      { id: 'kpi-002-6', name: '安全隐患排查', weight: 5, targetValue: '季度0高危', description: '安全漏洞发现及修复情况' },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'kpi-003',
    name: '销售绩效考核模板',
    position: '销售经理',
    items: [
      { id: 'kpi-003-1', name: '签单金额', weight: 40, targetValue: '月度≥30万', description: '当月实际签约合同金额' },
      { id: 'kpi-003-2', name: '新客户开发', weight: 20, targetValue: '月度≥5个', description: '新增有效意向客户数量' },
      { id: 'kpi-003-3', name: '客户转化率', weight: 15, targetValue: '≥20%', description: '意向客户转化为签约客户的比率' },
      { id: 'kpi-003-4', name: '回款率', weight: 15, targetValue: '≥85%', description: '已签合同的回款执行情况' },
      { id: 'kpi-003-5', name: '客户满意度', weight: 10, targetValue: 'NPS≥8', description: '客户满意度调查及转介绍率' },
    ],
    createdAt: '2026-01-15',
  },
]

export const PERFORMANCE_RECORDS: PerformanceRecord[] = [
  {
    id: 'perf-001',
    employeeId: 'emp-002',
    employeeName: '王建国',
    departmentName: '技术部',
    period: '2026-06',
    periodType: '月度',
    kpiItems: [
      { id: 'kpi-002-1', name: '需求交付及时率', weight: 25, targetValue: '≥95%', description: '按排期准时交付需求的比例', actualValue: '98%', score: 95 },
      { id: 'kpi-002-2', name: '系统稳定性', weight: 25, targetValue: '可用性≥99.9%', description: '服务可用性、故障响应及修复速度', actualValue: '99.95%', score: 96 },
      { id: 'kpi-002-3', name: '代码质量', weight: 20, targetValue: 'CR通过率≥90%', description: '代码评审通过率及线上Bug数', actualValue: '95%', score: 92 },
      { id: 'kpi-002-4', name: '接口性能', weight: 15, targetValue: 'P99<200ms', description: '核心接口响应时间及吞吐量', actualValue: '150ms', score: 90 },
      { id: 'kpi-002-5', name: '技术沉淀', weight: 10, targetValue: '月度≥1篇', description: '技术文档、架构设计文档输出', actualValue: '2篇', score: 95 },
      { id: 'kpi-002-6', name: '安全隐患排查', weight: 5, targetValue: '季度0高危', description: '安全漏洞发现及修复情况', actualValue: '0高危', score: 100 },
    ],
    totalScore: 95,
    grade: 'S',
    coefficient: 1.5,
    managerComment: '技术能力突出，主导完成系统架构升级，线上零故障，表现优异',
    employeeConfirmStatus: '已确认',
    bossReviewStatus: '已复核',
    aiBiasWarning: null,
  },
  {
    id: 'perf-002',
    employeeId: 'emp-001',
    employeeName: '陈志远',
    departmentName: '前端组',
    period: '2026-06',
    periodType: '月度',
    kpiItems: [
      { id: 'kpi-001-1', name: '需求交付及时率', weight: 30, targetValue: '≥95%', description: '按排期准时交付需求的比例', actualValue: '92%', score: 85 },
      { id: 'kpi-001-2', name: '代码质量', weight: 25, targetValue: 'CR通过率≥90%', description: '代码评审通过率及Bug数量', actualValue: '88%', score: 82 },
      { id: 'kpi-001-3', name: '页面性能优化', weight: 15, targetValue: 'LCP<2s', description: '核心页面加载性能指标', actualValue: '1.8s', score: 88 },
      { id: 'kpi-001-4', name: '技术分享与沉淀', weight: 10, targetValue: '月度≥1次', description: '技术分享、文档沉淀、组件复用贡献', actualValue: '1次', score: 80 },
      { id: 'kpi-001-5', name: '团队协作', weight: 10, targetValue: '360评分≥80', description: '跨部门协作满意度及沟通效率', actualValue: '85分', score: 85 },
      { id: 'kpi-001-6', name: '自驱学习', weight: 10, targetValue: '季度≥1项新技术', description: '主动学习新技术并应用于项目', actualValue: '已完成', score: 90 },
    ],
    totalScore: 85,
    grade: 'A',
    coefficient: 1.2,
    managerComment: '整体表现良好，前端组件库建设有进展，交付质量稳定',
    employeeConfirmStatus: '已确认',
    bossReviewStatus: '已复核',
    aiBiasWarning: null,
  },
  {
    id: 'perf-003',
    employeeId: 'emp-006',
    employeeName: '周海涛',
    departmentName: '销售部',
    period: '2026-06',
    periodType: '月度',
    kpiItems: [
      { id: 'kpi-003-1', name: '签单金额', weight: 40, targetValue: '月度≥30万', description: '当月实际签约合同金额', actualValue: '42万', score: 95 },
      { id: 'kpi-003-2', name: '新客户开发', weight: 20, targetValue: '月度≥5个', description: '新增有效意向客户数量', actualValue: '6个', score: 88 },
      { id: 'kpi-003-3', name: '客户转化率', weight: 15, targetValue: '≥20%', description: '意向客户转化为签约客户的比率', actualValue: '25%', score: 90 },
      { id: 'kpi-003-4', name: '回款率', weight: 15, targetValue: '≥85%', description: '已签合同的回款执行情况', actualValue: '90%', score: 92 },
      { id: 'kpi-003-5', name: '客户满意度', weight: 10, targetValue: 'NPS≥8', description: '客户满意度调查及转介绍率', actualValue: 'NPS 9', score: 95 },
    ],
    totalScore: 92,
    grade: 'S',
    coefficient: 1.5,
    managerComment: '连续3个月超额完成业绩目标，广州客户开发有突破性进展',
    employeeConfirmStatus: '已确认',
    bossReviewStatus: '已复核',
    aiBiasWarning: null,
  },
  {
    id: 'perf-004',
    employeeId: 'emp-007',
    employeeName: '林美玲',
    departmentName: '运营部',
    period: '2026-06',
    periodType: '月度',
    kpiItems: [
      { id: 'kpi-006-1', name: '账号增长', weight: 30, targetValue: '月涨粉≥5000', description: '负责账号粉丝增长情况', actualValue: '4200', score: 75 },
      { id: 'kpi-006-2', name: '内容产出', weight: 25, targetValue: '月度≥20条', description: '短视频及图文内容产出数量', actualValue: '22条', score: 85 },
      { id: 'kpi-006-3', name: '互动率', weight: 20, targetValue: '≥5%', description: '内容平均互动率(点赞+评论+转发/播放)', actualValue: '4.2%', score: 72 },
      { id: 'kpi-006-4', name: '转化线索', weight: 15, targetValue: '月度≥10条', description: '通过运营获取的有效销售线索', actualValue: '8条', score: 70 },
      { id: 'kpi-006-5', name: '数据分析', weight: 10, targetValue: '周报准时率100%', description: '运营数据复盘及策略调整', actualValue: '100%', score: 90 },
    ],
    totalScore: 78,
    grade: 'B',
    coefficient: 1.0,
    managerComment: '内容产出稳定，但涨粉未达预期，需优化选题方向和发布时间策略',
    employeeConfirmStatus: '待确认',
    bossReviewStatus: '待复核',
    aiBiasWarning: null,
  },
  {
    id: 'perf-005',
    employeeId: 'emp-003',
    employeeName: '刘思琪',
    departmentName: '后端组',
    period: '2026-06',
    periodType: '月度',
    kpiItems: [
      { id: 'kpi-002-1', name: '需求交付及时率', weight: 25, targetValue: '≥95%', description: '按排期准时交付需求的比例', actualValue: '85%', score: 70 },
      { id: 'kpi-002-2', name: '系统稳定性', weight: 25, targetValue: '可用性≥99.9%', description: '服务可用性、故障响应及修复速度', actualValue: '99.5%', score: 75 },
      { id: 'kpi-002-3', name: '代码质量', weight: 20, targetValue: 'CR通过率≥90%', description: '代码评审通过率及线上Bug数', actualValue: '82%', score: 68 },
      { id: 'kpi-002-4', name: '接口性能', weight: 15, targetValue: 'P99<200ms', description: '核心接口响应时间及吞吐量', actualValue: '280ms', score: 60 },
      { id: 'kpi-002-5', name: '技术沉淀', weight: 10, targetValue: '月度≥1篇', description: '技术文档、架构设计文档输出', actualValue: '0篇', score: 40 },
      { id: 'kpi-002-6', name: '安全隐患排查', weight: 5, targetValue: '季度0高危', description: '安全漏洞发现及修复情况', actualValue: '1中危', score: 60 },
    ],
    totalScore: 68,
    grade: 'C',
    coefficient: 0.8,
    managerComment: '入职时间较短，技术能力仍在成长中，交付效率有待提升，建议加强技术培训',
    employeeConfirmStatus: '已确认',
    bossReviewStatus: '已复核',
    aiBiasWarning: '该员工入职不满1年，建议结合成长曲线综合评估，避免新员工绩效偏低的系统性偏差',
  },
  {
    id: 'perf-006',
    employeeId: 'emp-005',
    employeeName: '孙小明',
    departmentName: '设计部',
    period: '2026-06',
    periodType: '月度',
    kpiItems: [
      { id: 'kpi-003-1', name: '设计交付及时率', weight: 30, targetValue: '≥95%', description: '按排期准时交付设计稿的比例', actualValue: '88%', score: 80 },
      { id: 'kpi-003-2', name: '设计质量', weight: 30, targetValue: '一次通过率≥80%', description: '设计方案一次通过评审的比例', actualValue: '70%', score: 65 },
      { id: 'kpi-003-3', name: '设计规范维护', weight: 20, targetValue: '组件库更新及时', description: '设计系统及组件库的维护更新', actualValue: '基本完成', score: 70 },
      { id: 'kpi-003-4', name: '跨部门协作', weight: 20, targetValue: '满意度≥80', description: '与产品、前端的协作效率', actualValue: '75分', score: 72 },
    ],
    totalScore: 72,
    grade: 'C',
    coefficient: 0.8,
    managerComment: '设计风格需要更贴合B端用户习惯，与前端的沟通效率有提升空间',
    employeeConfirmStatus: '已确认',
    bossReviewStatus: '待复核',
    aiBiasWarning: null,
  },
]

export const PAYROLL_RECORDS: PayrollRecord[] = [
  {
    id: 'pay-001',
    employeeId: 'emp-002',
    employeeName: '王建国',
    departmentName: '技术部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualWorkDays: 23,
    baseSalary: 28000,
    dailySalary: 1217,
    probationSalary: 0,
    isProbation: false,
    trialResult: '不适用',
    performanceBase: 8000,
    performanceCoefficient: 1.5,
    performancePay: 12000,
    attendanceDeduction: 0,
    socialInsurance: 4200,
    tax: 3180,
    totalDeduction: 7380,
    netSalary: 32620,
    status: '已审批',
    confirmStatus: '已确认',
    confirmedAt: '2026-07-25T14:30:00',
    confirmedIp: '192.168.1.100',
    aiAnomalyNote: null,
  },
  {
    id: 'pay-002',
    employeeId: 'emp-001',
    employeeName: '陈志远',
    departmentName: '前端组',
    year: 2026,
    month: 7,
    workDays: 23,
    actualWorkDays: 22,
    baseSalary: 18000,
    dailySalary: 783,
    probationSalary: 0,
    isProbation: false,
    trialResult: '不适用',
    performanceBase: 5000,
    performanceCoefficient: 1.2,
    performancePay: 6000,
    attendanceDeduction: 0,
    socialInsurance: 2700,
    tax: 1560,
    totalDeduction: 4260,
    netSalary: 19740,
    status: '已发放',
    confirmStatus: '已确认',
    confirmedAt: '2026-07-26T09:15:00',
    confirmedIp: '192.168.1.101',
    aiAnomalyNote: null,
  },
  {
    id: 'pay-003',
    employeeId: 'emp-006',
    employeeName: '周海涛',
    departmentName: '销售部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualWorkDays: 20,
    baseSalary: 20000,
    dailySalary: 870,
    probationSalary: 0,
    isProbation: false,
    trialResult: '不适用',
    performanceBase: 10000,
    performanceCoefficient: 1.5,
    performancePay: 15000,
    attendanceDeduction: 0,
    socialInsurance: 3000,
    tax: 3600,
    totalDeduction: 6600,
    netSalary: 28400,
    status: '已发放',
    confirmStatus: '已确认',
    confirmedAt: '2026-07-26T10:00:00',
    confirmedIp: '192.168.1.102',
    aiAnomalyNote: null,
  },
  {
    id: 'pay-004',
    employeeId: 'emp-011',
    employeeName: '郑雨萱',
    departmentName: '运营部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualWorkDays: 23,
    baseSalary: 9000,
    dailySalary: 391,
    probationSalary: 8000,
    isProbation: true,
    trialResult: '已通过',
    performanceBase: 2000,
    performanceCoefficient: 1.0,
    performancePay: 2000,
    attendanceDeduction: 0,
    socialInsurance: 1350,
    tax: 180,
    totalDeduction: 1530,
    netSalary: 8470,
    status: '待复核',
    confirmStatus: '待确认',
    confirmedAt: null,
    confirmedIp: null,
    aiAnomalyNote: '试用期员工薪资按转正工资的89%执行，已自动扣除社保个人部分',
  },
  {
    id: 'pay-005',
    employeeId: 'emp-010',
    employeeName: '黄伟杰',
    departmentName: '前端组',
    year: 2026,
    month: 7,
    workDays: 23,
    actualWorkDays: 5,
    baseSalary: 12000,
    dailySalary: 522,
    probationSalary: 0,
    isProbation: false,
    trialResult: '不适用',
    performanceBase: 3000,
    performanceCoefficient: 0,
    performancePay: 0,
    attendanceDeduction: 0,
    socialInsurance: 0,
    tax: 0,
    totalDeduction: 0,
    netSalary: 2610,
    status: '计算中',
    confirmStatus: '待确认',
    confirmedAt: null,
    confirmedIp: null,
    aiAnomalyNote: '试岗期员工，仅计算试岗天数工资，不参与绩效考核，不缴纳社保',
  },
  {
    id: 'pay-006',
    employeeId: 'emp-007',
    employeeName: '林美玲',
    departmentName: '运营部',
    year: 2026,
    month: 7,
    workDays: 23,
    actualWorkDays: 23,
    baseSalary: 10000,
    dailySalary: 435,
    probationSalary: 0,
    isProbation: false,
    trialResult: '不适用',
    performanceBase: 2000,
    performanceCoefficient: 1.0,
    performancePay: 2000,
    attendanceDeduction: 0,
    socialInsurance: 1500,
    tax: 360,
    totalDeduction: 1860,
    netSalary: 10140,
    status: '待老板审批',
    confirmStatus: '待确认',
    confirmedAt: null,
    confirmedIp: null,
    aiAnomalyNote: null,
  },
]

export const RESIGNATION_RECORDS: ResignationRecord[] = [
  {
    id: 'res-001',
    employeeId: 'emp-012',
    employeeName: '何志强',
    departmentName: '测试组',
    position: '测试工程师',
    resignationDate: '2026-06-15',
    lastWorkDate: '2026-07-15',
    reason: '个人职业规划调整，计划转行做产品经理',
    status: '已完成',
    projectHandovers: [
      { projectName: 'CRM系统测试', handoverTo: 'emp-003', handoverToName: '刘思琪', status: '已交接' },
      { projectName: '电商平台自动化测试', handoverTo: 'emp-001', handoverToName: '陈志远', status: '已交接' },
    ],
    customerHandovers: [],
    assetReturns: [
      { assetName: 'MacBook Pro 14寸', assetNo: 'IT-2025-0312', returned: true, returnedAt: '2026-07-14T16:00:00' },
      { assetName: '显示器 27寸', assetNo: 'IT-2025-0313', returned: true, returnedAt: '2026-07-14T16:00:00' },
    ],
    salarySettlement: '已结清7月工资，按实际出勤15天计算，补发年假折算1天',
    hookStatus: {
      wecomDisabled: true,
      oaDisabled: true,
      systemDisabled: true,
      hookLog: [
        { action: '企业微信账号禁用', timestamp: '2026-07-15T18:00:00', result: '成功' },
        { action: 'OA系统账号禁用', timestamp: '2026-07-15T18:00:01', result: '成功' },
        { action: '代码仓库权限回收', timestamp: '2026-07-15T18:00:02', result: '成功' },
      ],
    },
  },
  {
    id: 'res-002',
    employeeId: '',
    employeeName: '马文博',
    departmentName: '销售部',
    position: '销售经理',
    resignationDate: '2026-07-20',
    lastWorkDate: '2026-08-20',
    reason: '家庭原因需回老家发展',
    status: '交接中',
    projectHandovers: [],
    customerHandovers: [
      { customerName: '深圳XX教育集团', handoverTo: 'emp-006', handoverToName: '周海涛', status: '待交接' },
      { customerName: '广州YY科技有限公司', handoverTo: 'emp-006', handoverToName: '周海涛', status: '待交接' },
      { customerName: '东莞ZZ制造有限公司', handoverTo: '', handoverToName: '', status: '待交接' },
    ],
    assetReturns: [
      { assetName: 'MacBook Air', assetNo: 'IT-2024-0198', returned: false, returnedAt: null },
      { assetName: '公司工牌', assetNo: 'BP-2024-0198', returned: false, returnedAt: null },
    ],
    salarySettlement: '待结算',
    hookStatus: {
      wecomDisabled: false,
      oaDisabled: false,
      systemDisabled: false,
      hookLog: [],
    },
  },
]

export const DISPATCHES: Dispatch[] = [
  {
    id: 'dsp-001',
    title: 'CRM系统需求评审',
    type: '项目',
    bizLineName: '软件定制开发',
    projectName: 'CRM客户管理系统',
    description: '组织产品、开发、测试三方完成V2.3版本需求评审，输出评审纪要',
    deadline: '2026-07-18',
    assignerId: 'emp-004',
    assignerName: '赵雅琴',
    assigneeId: 'emp-001',
    assigneeName: '陈志远',
    actualHours: 4,
    feedback: '已完成需求评审，共确认12个需求点，3个待澄清',
    status: '已验收',
    createdAt: '2026-07-14T09:00:00',
    completedAt: '2026-07-17T18:00:00',
    autoCompleted: false,
  },
  {
    id: 'dsp-002',
    title: '办公室网络设备更换',
    type: '行政',
    bizLineName: '软件定制开发',
    projectName: '行政事务',
    description: '3楼会议室路由器故障，需采购并更换为华为AX3 Pro',
    deadline: '2026-07-20',
    assignerId: 'emp-008',
    assignerName: '吴静怡',
    assigneeId: 'emp-005',
    assigneeName: '孙小明',
    actualHours: 0,
    feedback: '',
    status: '进行中',
    createdAt: '2026-07-16T10:00:00',
    completedAt: null,
    autoCompleted: false,
  },
  {
    id: 'dsp-003',
    title: '移民业务推广视频制作',
    type: '项目',
    bizLineName: 'IP打造',
    projectName: '移民IP孵化',
    description: '为移民业务线制作3条短视频素材，内容包括成功案例分享、政策解读、办理流程科普',
    deadline: '2026-07-25',
    assignerId: 'emp-006',
    assignerName: '周海涛',
    assigneeId: 'emp-007',
    assigneeName: '林美玲',
    actualHours: 0,
    feedback: '',
    status: '待接单',
    createdAt: '2026-07-22T14:00:00',
    completedAt: null,
    autoCompleted: false,
  },
  {
    id: 'dsp-004',
    title: '电商后台数据看板开发',
    type: '项目',
    bizLineName: '电商业务',
    projectName: '电商平台运营系统',
    description: '开发电商后台数据看板模块，包含GMV趋势图、SKU销量排行、转化漏斗图',
    deadline: '2026-07-28',
    assignerId: 'emp-004',
    assignerName: '赵雅琴',
    assigneeId: 'emp-003',
    assigneeName: '刘思琪',
    actualHours: 0,
    feedback: '',
    status: '进行中',
    createdAt: '2026-07-15T09:30:00',
    completedAt: null,
    autoCompleted: false,
  },
  {
    id: 'dsp-005',
    title: '月度团建活动策划',
    type: '行政',
    bizLineName: '软件定制开发',
    projectName: '行政事务',
    description: '策划7月团建活动，预算3000元，需包含团队协作类游戏和聚餐',
    deadline: '2026-07-22',
    assignerId: 'emp-009',
    assignerName: '张明华',
    assigneeId: 'emp-008',
    assigneeName: '吴静怡',
    actualHours: 6,
    feedback: '已策划完成，方案为大鹏较场尾海边烧烤+沙滩排球，预算2800元',
    status: '待验收',
    createdAt: '2026-07-10T11:00:00',
    completedAt: null,
    autoCompleted: false,
  },
  {
    id: 'dsp-006',
    title: '客户合同模板更新',
    type: '行政',
    bizLineName: '移民业务',
    projectName: '行政事务',
    description: '根据最新法规更新移民服务合同模板，增加数据隐私条款和免责声明',
    deadline: '2026-07-15',
    assignerId: 'emp-008',
    assignerName: '吴静怡',
    assigneeId: 'emp-004',
    assigneeName: '赵雅琴',
    actualHours: 3,
    feedback: '',
    status: '超时自动结单',
    createdAt: '2026-07-08T09:00:00',
    completedAt: '2026-07-15T23:59:59',
    autoCompleted: true,
  },
]

export const DASHBOARD_STATS: DashboardStats = {
  totalEmployees: 11,
  onTrial: 1,
  probation: 1,
  resignedThisMonth: 1,
  totalSalaryCost: 154140,
  avgPerformanceScore: 82.5,
  attendanceRate: 96.8,
  dispatchCompletionRate: 75,
}
