// ========================================
// 线索管理模块 - Mock 数据
// ========================================

import type { Lead, FollowRecord } from './types';

// ==================== 线索 Mock 数据 ====================

export const mockLeads: Lead[] = [
  {
    id: '1',
    leadNo: '5872',
    name: '小程序开发',
    contactName: '',
    phone: '',
    wechat: '',
    source: '小红书',
    leadType: '已认领',
    stage: '待跟进',
    entity: '中科软通',
    ownerId: 'emp-001',
    ownerName: '闻杨',
    creatorId: 'emp-001',
    creatorName: '闻杨',
    createTime: '2026-07-24 10:05',
    updateTime: '2026-07-24 10:05',
  },
  {
    id: '2',
    leadNo: '5871',
    name: '展会导览小程序开发',
    contactName: '',
    phone: '',
    wechat: '',
    source: '小红书',
    customerType: 'C类',
    leadType: '已认领',
    stage: '联系不上',
    intentLevel: '意向低',
    entity: '中科软通',
    preSaleGroupName: '【0723】展厅导览小...',
    ownerId: 'emp-002',
    ownerName: '周杨',
    creatorId: 'emp-002',
    creatorName: '周杨',
    createTime: '2026-07-23 15:33',
    updateTime: '2026-07-23 15:33',
  },
  {
    id: '3',
    leadNo: '5870',
    name: '驼奶羊奶AI智能体',
    contactName: '',
    phone: '',
    wechat: '',
    source: '其他',
    leadType: '已认领',
    stage: '待跟进',
    intentLevel: '意向中',
    entity: '中科软通',
    preSaleGroupName: '【7.23】驼奶羊奶AI...',
    ownerId: 'emp-003',
    ownerName: '吴丹丹',
    creatorId: 'emp-003',
    creatorName: '吴丹丹',
    createTime: '2026-07-23 15:32',
    updateTime: '2026-07-23 15:32',
  },
  {
    id: '4',
    leadNo: '5869',
    name: '小程序开发',
    contactName: '',
    phone: '19858155546',
    wechat: '19858155546',
    source: '小红书',
    leadType: '已认领',
    stage: '初步建联',
    intentLevel: '意向中',
    entity: '中科软通',
    ownerId: 'emp-003',
    ownerName: '吴丹丹',
    creatorId: 'emp-003',
    creatorName: '吴丹丹',
    createTime: '2026-07-23 09:24',
    updateTime: '2026-07-24 10:00',
    lastFollowTime: '2026-07-24 10:00',
    nextFollowTime: '2026-07-25 10:00',
  },
  {
    id: '5',
    leadNo: '5868',
    name: '销售易crm可以做吗',
    contactName: '',
    phone: '',
    wechat: '',
    source: '小红书',
    customerType: 'C类',
    leadType: '公海',
    stage: '待分配',
    intentLevel: '意向低',
    entity: '中科软通',
    preSaleGroupName: '【0721】企业微信对...',
    ownerId: 'emp-001',
    ownerName: '闻杨',
    creatorId: 'emp-001',
    creatorName: '闻杨',
    historyOwners: [
      { ownerId: 'emp-001', ownerName: '闻杨', transferTime: '2026-07-21 16:57' },
    ],
    createTime: '2026-07-21 16:57',
    updateTime: '2026-07-21 16:57',
  },
  {
    id: '6',
    leadNo: '5867',
    name: '家具APP开发',
    contactName: '刘火圣',
    phone: '19070253156',
    wechat: 'Suzaojia88',
    source: '小红书',
    customerType: 'C类',
    leadType: '已认领',
    stage: '方案报价',
    intentLevel: '意向低',
    entity: '中科软通',
    preSaleGroupName: '【0721】家具小程序...',
    ownerId: 'emp-001',
    ownerName: '闻杨',
    creatorId: 'emp-001',
    creatorName: '闻杨',
    createTime: '2026-07-21 16:55',
    updateTime: '2026-07-24 13:58',
    lastFollowTime: '2026-07-24 13:58',
    nextFollowTime: '2026-07-25 10:00',
    attachments: [
      { id: 'att-1', name: '报价单.pdf', size: '256KB' },
    ],
  },
  {
    id: '7',
    leadNo: '5866',
    name: '汽车配件索赔系统',
    contactName: '',
    phone: '',
    wechat: '',
    source: '小红书',
    customerType: 'A类',
    leadType: '已认领',
    stage: '出demo中',
    intentLevel: '意向中',
    entity: '中科软通',
    preSaleGroupName: '汽车配件索赔系统客...',
    ownerId: 'emp-003',
    ownerName: '吴丹丹',
    creatorId: 'emp-003',
    creatorName: '吴丹丹',
    createTime: '2026-07-21 15:55',
    updateTime: '2026-07-21 15:55',
  },
  {
    id: '8',
    leadNo: '5865',
    name: '代扫码评价的软件或小...',
    contactName: '',
    phone: '',
    wechat: '',
    source: '小红书',
    customerType: 'C类',
    leadType: '公海',
    stage: '待分配',
    intentLevel: '意向低',
    entity: '中科软通',
    ownerId: 'emp-001',
    ownerName: '闻杨',
    creatorId: 'emp-001',
    creatorName: '闻杨',
    historyOwners: [
      { ownerId: 'emp-001', ownerName: '闻杨', transferTime: '2026-07-21 13:58' },
    ],
    createTime: '2026-07-21 13:58',
    updateTime: '2026-07-21 13:58',
  },
  {
    id: '9',
    leadNo: '5864',
    name: '连锁美业公司的收银系...',
    contactName: '',
    phone: '',
    wechat: '',
    source: '威客',
    leadType: '公海',
    stage: '待分配',
    intentLevel: '意向低',
    entity: '中科软通',
    ownerId: 'emp-003',
    ownerName: '吴丹丹',
    creatorId: 'emp-003',
    creatorName: '吴丹丹',
    historyOwners: [
      { ownerId: 'emp-003', ownerName: '吴丹丹', transferTime: '2026-07-21 13:56' },
    ],
    createTime: '2026-07-21 13:56',
    updateTime: '2026-07-21 13:56',
  },
  {
    id: '10',
    leadNo: '5863',
    name: 'Android医疗APP定制开',
    contactName: '',
    phone: '',
    wechat: '',
    source: '威客',
    customerType: 'C类',
    leadType: '公海',
    stage: '待分配',
    intentLevel: '意向低',
    entity: '中科软通',
    ownerId: 'emp-001',
    ownerName: '闻杨',
    creatorId: 'emp-001',
    creatorName: '闻杨',
    historyOwners: [
      { ownerId: 'emp-001', ownerName: '闻杨', transferTime: '2026-07-21 13:41' },
    ],
    createTime: '2026-07-21 13:41',
    updateTime: '2026-07-21 13:41',
  },
  // 已分配线索
  {
    id: '11',
    leadNo: '5843',
    name: '创艺复色二期',
    contactName: '',
    phone: '',
    wechat: '',
    source: '威客',
    leadType: '已认领',
    stage: '待跟进',
    entity: '中科软通',
    preSaleGroupName: '【服装上门预约小程...',
    ownerId: 'emp-004',
    ownerName: '周欢',
    creatorId: 'emp-004',
    creatorName: '周欢',
    createTime: '2026-07-14 17:31',
    updateTime: '2026-07-14 17:31',
  },
  {
    id: '12',
    leadNo: '4913',
    name: '医疗陪诊小程序',
    contactName: '',
    phone: '',
    wechat: '',
    source: '百度',
    customerType: 'A类',
    leadType: '已认领',
    stage: '待跟进',
    intentLevel: '意向中',
    entity: '中科软通',
    preSaleGroupName: '【0511】医疗陪诊平...',
    ownerId: 'emp-001',
    ownerName: '闻杨',
    creatorId: 'emp-001',
    creatorName: '闻杨',
    historyOwners: [
      { ownerId: 'emp-005', ownerName: '郭豪杰', transferTime: '2026-05-11 13:48', reason: '转手4次' },
    ],
    createTime: '2026-05-11 13:48',
    updateTime: '2026-05-11 13:48',
  },
  // 高新企业线索
  {
    id: '13',
    leadNo: '4960',
    name: '武汉思维通达软件有限...',
    contactName: '',
    phone: '',
    wechat: '',
    source: '高企名单',
    leadType: '高企名单',
    stage: '待跟进',
    entity: '中科软齐',
    ownerId: 'emp-006',
    ownerName: '陈丹丹',
    creatorId: 'emp-006',
    creatorName: '陈丹丹',
    createTime: '2026-05-12 00:00',
    updateTime: '2026-05-12 00:00',
  },
  {
    id: '14',
    leadNo: '4961',
    name: '襄阳鑫航联达科技有限...',
    contactName: '',
    phone: '',
    wechat: '',
    source: '高企名单',
    leadType: '高企名单',
    stage: '联系不上',
    intentLevel: '意向低',
    entity: '中科软齐',
    ownerId: 'emp-006',
    ownerName: '陈丹丹',
    creatorId: 'emp-006',
    creatorName: '陈丹丹',
    createTime: '2026-05-12 00:00',
    updateTime: '2026-05-12 00:00',
  },
  {
    id: '15',
    leadNo: '6001',
    name: '企业OA管理系统定制开发',
    contactName: '王总',
    phone: '13800138000',
    wechat: 'wangzong_oa',
    source: '百度',
    customerType: 'A类',
    leadType: '已认领',
    stage: '已签单',
    intentLevel: '意向高',
    budget: '15万',
    entity: '中科软通',
    preSaleGroupName: '【0601】企业OA管理系统',
    ownerId: 'emp-001',
    ownerName: '闻杨',
    creatorId: 'emp-001',
    creatorName: '闻杨',
    projectId: '1',
    contractId: '1',
    remark: '客户是某中型企业，需要定制OA管理系统，包含审批流程、考勤、日报等模块',
    createTime: '2026-06-01 10:00',
    updateTime: '2026-07-15 14:30',
    lastFollowTime: '2026-07-15 14:30',
  },
];

// ==================== 跟进记录 Mock 数据 ====================

export const mockFollowRecords: FollowRecord[] = [
  {
    id: 'follow-1',
    leadId: '6',
    leadNo: '5867',
    leadName: '家具APP开发',
    method: '微信沟通',
    stage: '方案报价',
    intentLevel: '意向低',
    content: '今天给客户那边报价了',
    duration: 1,
    followerId: 'emp-001',
    followerName: '闻杨',
    nextFollowTime: '2026-07-25 10:00',
    createTime: '2026-07-24 13:58',
    leadInfo: {
      preSaleGroupName: '【0721】家具小程序...',
      contactName: '刘火圣',
      phone: '19070253156',
      wechat: 'Suzaojia88',
    },
  },
  {
    id: 'follow-2',
    leadId: '6',
    leadNo: '5867',
    leadName: '家具APP开发',
    method: '微信沟通',
    stage: '方案报价',
    intentLevel: '意向低',
    content: '给客户做了报价清单，小程序1.5w，h5是1w，两个一起1.8w，带后台管理，客户那边还没有回复',
    duration: 1,
    followerId: 'emp-001',
    followerName: '闻杨',
    nextFollowTime: '2026-07-24 10:00',
    createTime: '2026-07-23 17:42',
    leadInfo: {
      preSaleGroupName: '【0721】家具小程序...',
      contactName: '刘火圣',
      phone: '19070253156',
      wechat: 'Suzaojia88',
    },
  },
  {
    id: 'follow-3',
    leadId: '6',
    leadNo: '5867',
    leadName: '家具APP开发',
    method: '微信沟通',
    stage: '初步建联',
    intentLevel: '意向低',
    content: '客户那边不确定是想做官网还是小程序，只是想用来展示产品，我这边问他需不需要后台管理系统，客户未回复',
    duration: 1,
    followerId: 'emp-001',
    followerName: '闻杨',
    nextFollowTime: '2026-07-23 10:00',
    createTime: '2026-07-22 11:04',
    leadInfo: {
      preSaleGroupName: '【0721】家具小程序...',
      contactName: '刘火圣',
      phone: '19070253156',
      wechat: 'Suzaojia88',
    },
  },
  {
    id: 'follow-4',
    leadId: '6',
    leadNo: '5867',
    leadName: '家具APP开发',
    method: '微信沟通',
    stage: '初步建联',
    intentLevel: '意向低',
    content: '拉群了',
    duration: 1,
    followerId: 'emp-001',
    followerName: '闻杨',
    nextFollowTime: '2026-07-22 10:00',
    createTime: '2026-07-21 17:32',
    leadInfo: {
      preSaleGroupName: '【0721】家具小程序...',
      contactName: '刘火圣',
      phone: '19070253156',
      wechat: 'Suzaojia88',
    },
  },
  {
    id: 'follow-5',
    leadId: '4',
    leadNo: '5869',
    leadName: '小程序开发',
    method: '微信沟通',
    stage: '初步建联',
    intentLevel: '意向中',
    content: '早上加的客户，下午才回复',
    duration: 1,
    followerId: 'emp-003',
    followerName: '吴丹丹',
    nextFollowTime: '2026-07-24 10:00',
    createTime: '2026-07-24 10:00',
    leadInfo: {
      phone: '19858155546',
      wechat: '19858155546',
    },
  },
];

// ==================== 员工数据 ====================

export const employees = [
  { id: 'emp-001', name: '闻杨' },
  { id: 'emp-002', name: '周杨' },
  { id: 'emp-003', name: '吴丹丹' },
  { id: 'emp-004', name: '周欢' },
  { id: 'emp-005', name: '郭豪杰' },
  { id: 'emp-006', name: '陈丹丹' },
  { id: 'emp-007', name: '黄奕' },
  { id: 'emp-008', name: '乐炎' },
];

// ==================== 对接主体 ====================

export const entities = ['中科软通', '中科软齐', '软艺信息', '巴蜀文攻'];
