// ========================================
// 差旅管理模块 - Mock 数据
// ========================================

import type {
  Trip,
  Reimbursement,
  Loan,
  DormitoryBuilding,
  PunchRecord,
  PunchRule,
  ExpenseStandard,
  TravelSubsidy,
} from './types';

// ==================== 出差单 Mock 数据 ====================

export const mockTrips: Trip[] = [
  {
    id: '1',
    tripNo: 'BT20260425001',
    applicantId: 'emp-001',
    applicantName: '张三',
    department: '销售部',
    customerId: 'cust-001',
    customerName: '阿里巴巴（中国）有限公司',
    projectId: 'proj-001',
    projectName: '阿里巴巴-企业管理系统',
    destinations: ['杭州'],
    startDate: '2026-04-28',
    endDate: '2026-04-30',
    days: 3,
    transportModes: ['high_speed_rail'],
    accommodationIntent: 'hotel',
    estimatedAccommodationDays: 2,
    estimatedTransportCost: 1000,
    estimatedAccommodationCost: 1200,
    estimatedMealCost: 600,
    estimatedOtherCost: 200,
    estimatedTotalCost: 3000,
    needLoan: true,
    loanAmount: 3000,
    loanReason: '出差备用金',
    status: 'approved',
    purpose: '项目需求调研和方案演示',
    createDate: '2026-04-25',
    updateDate: '2026-04-25',
    itinerarySegments: [
      {
        id: 'seg-1-1',
        tripId: '1',
        segmentOrder: 1,
        departure: '北京',
        destination: '杭州',
        departureDate: '2026-04-28',
        arrivalDate: '2026-04-28',
        transportMode: 'high_speed_rail',
        transportDetail: 'G101',
        transportCost: 500,
        customerId: 'cust-001',
        customerName: '阿里巴巴（中国）有限公司',
        projectId: 'proj-001',
        projectName: '阿里巴巴-企业管理系统',
        accommodation: {
          id: 'acc-1-1',
          itinerarySegmentId: 'seg-1-1',
          type: 'hotel',
          hotelName: '杭州西湖国宾馆',
          roomType: '大床房',
          pricePerNight: 600,
          nights: 2,
          totalAmount: 1200,
        },
        expenses: [
          {
            id: 'exp-1-1',
            tripId: '1',
            itinerarySegmentId: 'seg-1-1',
            type: 'meal',
            amount: 200,
            date: '2026-04-28',
            isOverStandard: false,
          },
          {
            id: 'exp-1-2',
            tripId: '1',
            itinerarySegmentId: 'seg-1-1',
            type: 'local_transport',
            amount: 100,
            date: '2026-04-28',
            isOverStandard: false,
          },
        ],
        totalExpense: 1800,
      },
      {
        id: 'seg-1-2',
        tripId: '1',
        segmentOrder: 2,
        departure: '杭州',
        destination: '北京',
        departureDate: '2026-04-30',
        arrivalDate: '2026-04-30',
        transportMode: 'high_speed_rail',
        transportDetail: 'G102',
        transportCost: 500,
        customerId: 'cust-001',
        customerName: '阿里巴巴（中国）有限公司',
        projectId: 'proj-001',
        projectName: '阿里巴巴-企业管理系统',
        expenses: [],
        totalExpense: 500,
      },
    ],
    loans: [
      {
        id: 'loan-1',
        loanNo: 'LN20260425001',
        applicantId: 'emp-001',
        applicantName: '张三',
        department: '销售部',
        tripId: '1',
        tripNo: 'BT20260425001',
        type: 'travel',
        amount: 3000,
        reason: '出差备用金',
        expectedPayDate: '2026-04-27',
        payMethod: 'bank',
        status: 'paid',
        createDate: '2026-04-25',
        updateDate: '2026-04-26',
        offsetAmount: 0,
        remainingAmount: 3000,
        approvalRecords: [
          {
            id: 'approval-1-1',
            step: '发起申请',
            approver: '张三',
            approverId: 'emp-001',
            status: 'approved',
            time: '2026-04-25 10:00',
            comment: '提交借款申请',
          },
          {
            id: 'approval-1-2',
            step: '部门主管审批',
            approver: '王经理',
            approverId: 'emp-002',
            status: 'approved',
            time: '2026-04-25 14:30',
            comment: '同意',
          },
          {
            id: 'approval-1-3',
            step: '财务审核',
            approver: '陈财务',
            approverId: 'emp-003',
            status: 'approved',
            time: '2026-04-26 09:00',
            comment: '已安排打款',
          },
        ],
      },
    ],
    subsidy: {
      id: 'sub-1',
      tripId: '1',
      calcMode: 'calendar_day',
      cityLevel: 'first_tier',
      standard: 150,
      days: 3,
      totalAmount: 450,
      workingDays: 2,
      overtimeDays: 0,
      isPaid: false,
    },
    approvalRecords: [
      {
        id: 'approval-trip-1-1',
        step: '发起申请',
        approver: '张三',
        approverId: 'emp-001',
        status: 'approved',
        time: '2026-04-25 10:00',
        comment: '提交出差申请',
      },
      {
        id: 'approval-trip-1-2',
        step: '部门主管审批',
        approver: '王经理',
        approverId: 'emp-002',
        status: 'approved',
        time: '2026-04-25 14:30',
        comment: '同意出差',
      },
      {
        id: 'approval-trip-1-3',
        step: '财务审核',
        approver: '陈财务',
        approverId: 'emp-003',
        status: 'approved',
        time: '2026-04-25 15:00',
        comment: '同意',
      },
    ],
  },
  {
    id: '2',
    tripNo: 'BT20260424001',
    applicantId: 'emp-004',
    applicantName: '李四',
    department: '销售部',
    customerId: 'cust-002',
    customerName: '腾讯科技（深圳）有限公司',
    destinations: ['深圳'],
    startDate: '2026-04-26',
    endDate: '2026-04-27',
    days: 2,
    transportModes: ['airplane'],
    accommodationIntent: 'hotel',
    estimatedAccommodationDays: 1,
    estimatedTransportCost: 2000,
    estimatedAccommodationCost: 800,
    estimatedMealCost: 300,
    estimatedOtherCost: 200,
    estimatedTotalCost: 3300,
    needLoan: false,
    status: 'to_reimburse',
    purpose: '客户拜访和合同签订',
    createDate: '2026-04-24',
    updateDate: '2026-04-27',
    itinerarySegments: [
      {
        id: 'seg-2-1',
        tripId: '2',
        segmentOrder: 1,
        departure: '北京',
        destination: '深圳',
        departureDate: '2026-04-26',
        arrivalDate: '2026-04-26',
        transportMode: 'airplane',
        transportDetail: 'CA1234',
        transportCost: 1000,
        customerId: 'cust-002',
        customerName: '腾讯科技（深圳）有限公司',
        accommodation: {
          id: 'acc-2-1',
          itinerarySegmentId: 'seg-2-1',
          type: 'hotel',
          hotelName: '深圳福田香格里拉',
          roomType: '标准间',
          pricePerNight: 800,
          nights: 1,
          totalAmount: 800,
        },
        expenses: [
          {
            id: 'exp-2-1',
            tripId: '2',
            itinerarySegmentId: 'seg-2-1',
            type: 'meal',
            amount: 150,
            date: '2026-04-26',
            isOverStandard: false,
          },
        ],
        totalExpense: 1950,
      },
      {
        id: 'seg-2-2',
        tripId: '2',
        segmentOrder: 2,
        departure: '深圳',
        destination: '北京',
        departureDate: '2026-04-27',
        arrivalDate: '2026-04-27',
        transportMode: 'airplane',
        transportDetail: 'CA5678',
        transportCost: 1000,
        customerId: 'cust-002',
        customerName: '腾讯科技（深圳）有限公司',
        expenses: [],
        totalExpense: 1000,
      },
    ],
    subsidy: {
      id: 'sub-2',
      tripId: '2',
      calcMode: 'calendar_day',
      cityLevel: 'first_tier',
      standard: 150,
      days: 2,
      totalAmount: 300,
      workingDays: 2,
      overtimeDays: 0,
      isPaid: false,
    },
    approvalRecords: [
      {
        id: 'approval-trip-2-1',
        step: '发起申请',
        approver: '李四',
        approverId: 'emp-004',
        status: 'approved',
        time: '2026-04-24 09:00',
        comment: '提交出差申请',
      },
      {
        id: 'approval-trip-2-2',
        step: '部门主管审批',
        approver: '王经理',
        approverId: 'emp-002',
        status: 'approved',
        time: '2026-04-24 10:30',
        comment: '批准',
      },
      {
        id: 'approval-trip-2-3',
        step: '财务审核',
        approver: '陈财务',
        approverId: 'emp-003',
        status: 'approved',
        time: '2026-04-24 15:00',
        comment: '同意',
      },
    ],
  },
  {
    id: '3',
    tripNo: 'BT20260423001',
    applicantId: 'emp-005',
    applicantName: '王五',
    department: '技术部',
    customerId: 'cust-003',
    customerName: '北京字节跳动科技有限公司',
    projectId: 'proj-003',
    projectName: '字节跳动-协作工具',
    destinations: ['上海', '杭州'],
    startDate: '2026-05-01',
    endDate: '2026-05-07',
    days: 7,
    transportModes: ['high_speed_rail', 'bullet_train'],
    accommodationIntent: 'dormitory',
    estimatedAccommodationDays: 6,
    estimatedTransportCost: 800,
    estimatedAccommodationCost: 0,
    estimatedMealCost: 1000,
    estimatedOtherCost: 200,
    estimatedTotalCost: 2000,
    needLoan: true,
    loanAmount: 2000,
    loanReason: '出差备用金',
    status: 'pending',
    purpose: '多点驻场开发',
    createDate: '2026-04-23',
    updateDate: '2026-04-23',
    approvalRecords: [
      {
        id: 'approval-trip-3-1',
        step: '发起申请',
        approver: '王五',
        approverId: 'emp-005',
        status: 'approved',
        time: '2026-04-23 10:00',
        comment: '提交出差申请',
      },
      {
        id: 'approval-trip-3-2',
        step: '部门主管审批',
        approver: '李主管',
        approverId: 'emp-006',
        status: 'pending',
        time: '',
        comment: '',
      },
    ],
  },
];

// ==================== 报销单 Mock 数据 ====================

export const mockReimbursements: Reimbursement[] = [
  {
    id: 'reb-1',
    reimbursementNo: 'RB20260425001',
    tripId: '2',
    tripNo: 'BT20260424001',
    applicantId: 'emp-004',
    applicantName: '李四',
    department: '销售部',
    items: [
      {
        id: 'item-1-1',
        reimbursementId: 'reb-1',
        expenseId: 'exp-2-1',
        expenseType: 'meal',
        description: '工作餐',
        amount: 150,
        itinerarySegmentId: 'seg-2-1',
        itinerarySegmentDesc: '北京→深圳',
      },
      {
        id: 'item-1-2',
        reimbursementId: 'reb-1',
        expenseId: 'seg-2-1',
        expenseType: 'transport',
        description: '北京→深圳机票',
        amount: 1000,
        itinerarySegmentId: 'seg-2-1',
        itinerarySegmentDesc: '北京→深圳',
      },
      {
        id: 'item-1-3',
        reimbursementId: 'reb-1',
        expenseId: 'acc-2-1',
        expenseType: 'accommodation',
        description: '深圳福田香格里拉1晚',
        amount: 800,
        itinerarySegmentId: 'seg-2-1',
        itinerarySegmentDesc: '北京→深圳',
      },
      {
        id: 'item-1-4',
        reimbursementId: 'reb-1',
        expenseId: 'seg-2-2',
        expenseType: 'transport',
        description: '深圳→北京机票',
        amount: 1000,
        itinerarySegmentId: 'seg-2-2',
        itinerarySegmentDesc: '深圳→北京',
      },
    ],
    totalAmount: 2950,
    loanOffsets: [],
    offsetAmount: 0,
    netAmount: 2950,
    attachments: [
      { id: 'att-1-1', name: '机票行程单.pdf', size: '256KB' },
      { id: 'att-1-2', name: '酒店发票.pdf', size: '512KB' },
    ],
    status: 'pending',
    remark: '深圳出差报销',
    createDate: '2026-04-28',
    updateDate: '2026-04-28',
    approvalRecords: [
      {
        id: 'approval-reb-1-1',
        step: '发起申请',
        approver: '李四',
        approverId: 'emp-004',
        status: 'approved',
        time: '2026-04-28 09:30',
        comment: '提交报销申请',
      },
      {
        id: 'approval-reb-1-2',
        step: '部门主管审批',
        approver: '王经理',
        approverId: 'emp-002',
        status: 'pending',
        time: '',
        comment: '',
      },
    ],
  },
];

// ==================== 借款单 Mock 数据 ====================

export const mockLoans: Loan[] = [
  {
    id: 'loan-1',
    loanNo: 'LN20260425001',
    applicantId: 'emp-001',
    applicantName: '张三',
    department: '销售部',
    tripId: '1',
    tripNo: 'BT20260425001',
    type: 'travel',
    amount: 3000,
    reason: '出差备用金',
    expectedPayDate: '2026-04-27',
    payMethod: 'bank',
    status: 'paid',
    createDate: '2026-04-25',
    updateDate: '2026-04-26',
    offsetAmount: 0,
    remainingAmount: 3000,
    approvalRecords: [
      {
        id: 'approval-loan-1-1',
        step: '发起申请',
        approver: '张三',
        approverId: 'emp-001',
        status: 'approved',
        time: '2026-04-25 10:00',
        comment: '提交借款申请',
      },
      {
        id: 'approval-loan-1-2',
        step: '部门主管审批',
        approver: '王经理',
        approverId: 'emp-002',
        status: 'approved',
        time: '2026-04-25 14:30',
        comment: '同意',
      },
      {
        id: 'approval-loan-1-3',
        step: '财务审核',
        approver: '陈财务',
        approverId: 'emp-003',
        status: 'approved',
        time: '2026-04-26 09:00',
        comment: '已安排打款',
      },
    ],
  },
  {
    id: 'loan-2',
    loanNo: 'LN20260420001',
    applicantId: 'emp-004',
    applicantName: '李四',
    department: '销售部',
    type: 'petty_cash',
    amount: 5000,
    reason: '销售部备用金',
    payMethod: 'bank',
    status: 'settled',
    createDate: '2026-04-20',
    updateDate: '2026-04-25',
    offsets: [
      {
        id: 'offset-1',
        loanId: 'loan-2',
        loanNo: 'LN20260420001',
        reimbursementId: 'reb-old',
        offsetAmount: 5000,
        offsetDate: '2026-04-25',
      },
    ],
    offsetAmount: 5000,
    remainingAmount: 0,
    approvalRecords: [
      {
        id: 'approval-loan-2-1',
        step: '发起申请',
        approver: '李四',
        approverId: 'emp-004',
        status: 'approved',
        time: '2026-04-20 09:00',
        comment: '提交借款申请',
      },
      {
        id: 'approval-loan-2-2',
        step: '部门主管审批',
        approver: '王经理',
        approverId: 'emp-002',
        status: 'approved',
        time: '2026-04-20 11:00',
        comment: '同意',
      },
      {
        id: 'approval-loan-2-3',
        step: '财务审核',
        approver: '陈财务',
        approverId: 'emp-003',
        status: 'approved',
        time: '2026-04-20 14:00',
        comment: '已安排打款',
      },
    ],
  },
];

// ==================== 宿舍 Mock 数据 ====================

export const mockDormitories: DormitoryBuilding[] = [
  {
    id: 'building-1',
    name: '杭州西湖公寓',
    companyId: 'company-001',
    companyName: '北京科技有限公司',
    city: '杭州',
    district: '西湖区',
    street: '文三路',
    community: '翠苑小区',
    address: '翠苑小区3栋',
    landlordName: '张房东',
    landlordPhone: '13800138001',
    landlordIdCard: '330100199001011234',
    leaseStartDate: '2026-01-01',
    leaseEndDate: '2026-12-31',
    monthlyRent: 8000,
    deposit: 16000,
    paymentMethod: 'quarterly',
    waterAccountNo: 'WS330100001',
    waterPayMethod: '公司代缴',
    electricityAccountNo: 'ED330100001',
    electricityPayMethod: '公司代缴',
    gasAccountNo: 'GS330100001',
    gasPayMethod: '公司代缴',
    internetAccountNo: 'CT330100001',
    internetProvider: '中国电信',
    internetMonthlyFee: 200,
    internetPayMethod: '公司代缴',
    status: 'active',
    floors: [
      {
        id: 'floor-1-1',
        buildingId: 'building-1',
        floorNumber: 1,
        roomCount: 4,
        rooms: [
          {
            id: 'room-1-1-1',
            buildingId: 'building-1',
            floorId: 'floor-1-1',
            roomNumber: '101',
            roomType: 'double',
            bedCount: 2,
            facilities: ['空调', '独卫', '阳台'],
            status: 'occupied',
            beds: [
              {
                id: 'bed-1-1-1-1',
                buildingId: 'building-1',
                floorId: 'floor-1-1',
                roomId: 'room-1-1-1',
                bedNumber: '1号床',
                status: 'occupied',
                occupantId: 'emp-007',
                occupantName: '赵六',
              },
              {
                id: 'bed-1-1-1-2',
                buildingId: 'building-1',
                floorId: 'floor-1-1',
                roomId: 'room-1-1-1',
                bedNumber: '2号床',
                status: 'available',
              },
            ],
          },
          {
            id: 'room-1-1-2',
            buildingId: 'building-1',
            floorId: 'floor-1-1',
            roomNumber: '102',
            roomType: 'single',
            bedCount: 1,
            facilities: ['空调', '独卫'],
            status: 'available',
            beds: [
              {
                id: 'bed-1-1-2-1',
                buildingId: 'building-1',
                floorId: 'floor-1-1',
                roomId: 'room-1-1-2',
                bedNumber: '1号床',
                status: 'available',
              },
            ],
          },
        ],
      },
      {
        id: 'floor-1-2',
        buildingId: 'building-1',
        floorNumber: 2,
        roomCount: 4,
        rooms: [
          {
            id: 'room-1-2-1',
            buildingId: 'building-1',
            floorId: 'floor-1-2',
            roomNumber: '201',
            roomType: 'quad',
            bedCount: 4,
            facilities: ['空调', '独卫', '阳台', '洗衣机'],
            status: 'available',
            beds: [
              {
                id: 'bed-1-2-1-1',
                buildingId: 'building-1',
                floorId: 'floor-1-2',
                roomId: 'room-1-2-1',
                bedNumber: '1号床',
                status: 'available',
              },
              {
                id: 'bed-1-2-1-2',
                buildingId: 'building-1',
                floorId: 'floor-1-2',
                roomId: 'room-1-2-1',
                bedNumber: '2号床',
                status: 'available',
              },
              {
                id: 'bed-1-2-1-3',
                buildingId: 'building-1',
                floorId: 'floor-1-2',
                roomId: 'room-1-2-1',
                bedNumber: '3号床',
                status: 'available',
              },
              {
                id: 'bed-1-2-1-4',
                buildingId: 'building-1',
                floorId: 'floor-1-2',
                roomId: 'room-1-2-1',
                bedNumber: '4号床',
                status: 'available',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'building-2',
    name: '上海浦东公寓',
    companyId: 'company-001',
    companyName: '北京科技有限公司',
    city: '上海',
    district: '浦东新区',
    street: '张江路',
    community: '张江人才公寓',
    address: '张江人才公寓5栋',
    landlordName: '李房东',
    landlordPhone: '13900139001',
    leaseStartDate: '2026-03-01',
    leaseEndDate: '2027-02-28',
    monthlyRent: 12000,
    deposit: 24000,
    paymentMethod: 'monthly',
    waterAccountNo: 'WS310000001',
    waterPayMethod: '公司代缴',
    electricityAccountNo: 'ED310000001',
    electricityPayMethod: '公司代缴',
    gasAccountNo: 'GS310000001',
    gasPayMethod: '公司代缴',
    internetAccountNo: 'CT310000001',
    internetProvider: '中国联通',
    internetMonthlyFee: 300,
    internetPayMethod: '公司代缴',
    status: 'active',
    floors: [
      {
        id: 'floor-2-1',
        buildingId: 'building-2',
        floorNumber: 1,
        roomCount: 3,
        rooms: [
          {
            id: 'room-2-1-1',
            buildingId: 'building-2',
            floorId: 'floor-2-1',
            roomNumber: '101',
            roomType: 'double',
            bedCount: 2,
            facilities: ['空调', '独卫', '阳台', '冰箱'],
            status: 'available',
            beds: [
              {
                id: 'bed-2-1-1-1',
                buildingId: 'building-2',
                floorId: 'floor-2-1',
                roomId: 'room-2-1-1',
                bedNumber: '1号床',
                status: 'available',
              },
              {
                id: 'bed-2-1-1-2',
                buildingId: 'building-2',
                floorId: 'floor-2-1',
                roomId: 'room-2-1-1',
                bedNumber: '2号床',
                status: 'available',
              },
            ],
          },
        ],
      },
    ],
  },
];

// ==================== 打卡 Mock 数据 ====================

export const mockPunchRecords: PunchRecord[] = [
  {
    id: 'punch-1',
    employeeId: 'emp-001',
    employeeName: '张三',
    punchTime: '2026-04-28 09:05',
    punchType: 'clock_in',
    punchMethod: 'gps',
    longitude: 120.1234,
    latitude: 30.2345,
    address: '浙江省杭州市西湖区文三路',
    accuracy: 10,
    isOnTrip: true,
    tripId: '1',
    tripNo: 'BT20260425001',
    status: 'normal',
  },
  {
    id: 'punch-2',
    employeeId: 'emp-001',
    employeeName: '张三',
    punchTime: '2026-04-28 18:30',
    punchType: 'clock_out',
    punchMethod: 'gps',
    longitude: 120.1234,
    latitude: 30.2345,
    address: '浙江省杭州市西湖区文三路',
    accuracy: 10,
    isOnTrip: true,
    tripId: '1',
    tripNo: 'BT20260425001',
    status: 'normal',
  },
  {
    id: 'punch-3',
    employeeId: 'emp-001',
    employeeName: '张三',
    punchTime: '2026-04-29 08:55',
    punchType: 'clock_in',
    punchMethod: 'gps',
    longitude: 120.1234,
    latitude: 30.2345,
    address: '浙江省杭州市西湖区文三路',
    accuracy: 15,
    isOnTrip: true,
    tripId: '1',
    tripNo: 'BT20260425001',
    status: 'normal',
  },
  {
    id: 'punch-4',
    employeeId: 'emp-001',
    employeeName: '张三',
    punchTime: '2026-04-29 19:00',
    punchType: 'overtime',
    punchMethod: 'gps',
    longitude: 120.1234,
    latitude: 30.2345,
    address: '浙江省杭州市西湖区文三路',
    accuracy: 10,
    isOnTrip: true,
    tripId: '1',
    tripNo: 'BT20260425001',
    status: 'normal',
  },
];

export const mockPunchRule: PunchRule = {
  id: 'rule-1',
  name: '默认打卡规则',
  workStartTime: '09:00',
  workEndTime: '18:00',
  flexibleMinutes: 30,
  companyLongitude: 116.4074,
  companyLatitude: 39.9042,
  companyRadius: 500,
  limitOnTrip: false,
  temporaryZones: [
    {
      id: 'zone-1',
      name: '阿里巴巴杭州园区',
      longitude: 120.1234,
      latitude: 30.2345,
      radius: 1000,
      startDate: '2026-04-28',
      endDate: '2026-04-30',
      tripId: '1',
      tripNo: 'BT20260425001',
      projectId: 'proj-001',
      projectName: '阿里巴巴-企业管理系统',
    },
  ],
  overtimeStartTime: '18:30',
  overtimeMinUnit: 0.5,
  overtimeNeedApproval: false,
  lateThresholdMinutes: 5,
  absentHandling: 'allow_makeup',
  makeupDeadlineDays: 3,
  isActive: true,
};

// ==================== 费用标准 Mock 数据 ====================

export const mockExpenseStandards: ExpenseStandard[] = [
  {
    id: 'std-1',
    name: '2026年差旅费用标准',
    effectiveDate: '2026-01-01',
    status: 'active',
    details: [
      {
        id: 'detail-1-1',
        standardId: 'std-1',
        levels: ['L1', 'L2', 'L3'],
        cityLevels: ['first_tier'],
        highSpeedRailClass: 'second',
        bulletTrainClass: 'second',
        airplaneClass: 'economy',
        selfDriveRate: 1.5,
        localTransportLimit: 100,
        hotelLimit: 400,
        hotelRoomType: '标间/大床房',
        mealAllowance: 100,
        entertainmentMealLimit: 200,
        communicationAllowance: 30,
        miscellaneousAllowance: 50,
        subsidyCalcMode: 'calendar_day',
        subsidyAmount: 100,
      },
      {
        id: 'detail-1-2',
        standardId: 'std-1',
        levels: ['L4', 'L5', 'L6'],
        cityLevels: ['first_tier'],
        highSpeedRailClass: 'first',
        bulletTrainClass: 'first',
        airplaneClass: 'economy',
        selfDriveRate: 2.0,
        localTransportLimit: 150,
        hotelLimit: 600,
        hotelRoomType: '大床房',
        mealAllowance: 150,
        entertainmentMealLimit: 300,
        communicationAllowance: 50,
        miscellaneousAllowance: 80,
        subsidyCalcMode: 'calendar_day',
        subsidyAmount: 150,
      },
      {
        id: 'detail-1-3',
        standardId: 'std-1',
        levels: ['L7', 'L8', 'L9', 'L10'],
        cityLevels: ['first_tier'],
        highSpeedRailClass: 'business',
        bulletTrainClass: 'first',
        airplaneClass: 'business',
        selfDriveRate: 2.5,
        localTransportLimit: 200,
        hotelLimit: 1000,
        hotelRoomType: '套房',
        mealAllowance: 200,
        entertainmentMealLimit: 500,
        communicationAllowance: 80,
        miscellaneousAllowance: 100,
        subsidyCalcMode: 'calendar_day',
        subsidyAmount: 200,
      },
      {
        id: 'detail-1-4',
        standardId: 'std-1',
        levels: ['L1', 'L2', 'L3'],
        cityLevels: ['second_tier', 'third_tier', 'other'],
        highSpeedRailClass: 'second',
        bulletTrainClass: 'second',
        airplaneClass: 'economy',
        selfDriveRate: 1.2,
        localTransportLimit: 80,
        hotelLimit: 300,
        hotelRoomType: '标间/大床房',
        mealAllowance: 80,
        entertainmentMealLimit: 150,
        communicationAllowance: 20,
        miscellaneousAllowance: 40,
        subsidyCalcMode: 'working_day',
        subsidyAmount: 80,
      },
    ],
    createDate: '2026-01-01',
    updateDate: '2026-01-01',
  },
];
